# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Edward Cruz
# Description of the Site
description: Game Developer, Programmer, Game Systems Designer
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Games, Game Developer, Unreal Engine, Unity, C-Sharp, C++, Programmer
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: sagecreations.ec@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: edward-cruz-sagecreations
github_username: SageCreations
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Edward Cruz
# URL for the Image of the Author
author-image: "/assets/images/profile pic design.png"
# 60 Words About the Author
author-about: Led a team of 5 and drove out a finished build of our game within 6 weeks. Conceptualized and implemented enemy ai controllers for a multitude of projects across different game engines. Built a player character controller that uses custom gravity and auto camera behavior so that player only needs a single joystick and face button to play. Released Defrain, a retro arcade-style game, onto the steam store. Placed 6th out of 70+ competitors in the state of Texas for the Technology Student Association coding competition 2016-2017.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/SageCreations

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
